### ISSUE TITLE
Fails to compile with newer firmware.

### ISSUE THREAD

**Issue by bjc** [cdisselkoen/Kaleidoscope-MacrosOnTheFly#11]
Given the documentation and a quick perusal of the source, it seems like this plugin is still using the old plugin API. Compile error is below:

> ditto:~/Arduino/Model01-Firmware% make flash
> BOARD_HARDWARE_PATH="/home/bjc/Arduino/hardware" /home/bjc/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope/bin//kaleidoscope-builder flash
> Building output/Model01-Firmware/Model01-Firmware (0.0.0-gv1.22-26-ga99e-dirty) ...
> /home/bjc/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-MacrosOnTheFly/src/Kaleidoscope/FlashOverride.cpp: In member function 'void kaleidoscope::FlashOverride::begin()':
> /home/bjc/Arduino/hardware/keyboardio/avr/libraries/Kaleidoscope-MacrosOnTheFly/src/Kaleidoscope/FlashOverride.cpp:42:16: error: 'class kaleidoscope::Kaleidoscope_' has no member named 'useLoopHook'
>    Kaleidoscope.useLoopHook(loopHook);
>                 ^
> exit status 1
> /home/bjc/Arduino/hardware/keyboardio/avr/build-tools/makefiles//rules.mk:72: recipe for target 'flash' failed
> make: *** [flash] Error 1

**Comment by lgnakano** [comment]
I was able to compile by replacing line 32 from MacrosOnTheFly.h with
class MacrosOnTheFly : public kaleidoscope::Plugin{
from the current 
class MacrosOnTheFly : public KaleidoscopePlugin {
