### ISSUE TITLE
Playback (on fn-prog) of a slot whose key has something on its function layer causes problems

### ISSUE THREAD

**Issue by tremby** [cdisselkoen/Kaleidoscope-MacrosOnTheFly#3]
I've put record on prog and playback on fn-prog. Recording to slot "a" seems to work OK (the keys light up as I expect, and I get the green flash when finishing), but playback doesn't seem to do what I want.

So from start to end, I press prog, then a. The keys are lit up. I type hello and press prog again. The keys flash green. I then press fn-prog then a. Nothing happens. If I press a again now, the clipboard contents are pasted. I think this is because I have fn-a mapped to middle mouse button, which pastes the X selection contents. I can keep pressing a and it keeps pasting. I have to press and release fn, and then the keyboard acts normally again.

I tried recording to ' instead, and this worked just fine. I have nothing mapped to fn-'.

I get similar results to "a" when recording to any key which has something mapped on its function layer.

I imagine this is related to the issue with having the record key on the function layer.

**Comment by cdisselkoen** [comment]
Yep, this is probably exactly the issue where Fn can erroneously stay activated after initiating recording and/or playback.  It's possible the issue happens with either play or record on the function layer.

Even if it is a known bug, thanks for making it an official GitHub issue - this way it can be officially tracked.

**Comment by cdisselkoen** [comment]
`5d40834` fixes this issue in my testing.

**Comment by glasser** [comment]
FWIW, I'm seeing a similar issue. I had mapped any to play and fn-any to prog. I programmed something on enter, but when I hit any enter to play it back, it does the equivalent of fn-enter (play a song).

I have OneShot on too... could be an incompatibility there.

**Comment by cdisselkoen** [comment]
Hi @glasser,

Have you experienced this on the most recent firmware (in particular, with the fix in `5d40834` applied)?  I had hoped/thought that that fixed this issue, but if it didn't, I'm very interested in knowing more.  It's also very possible that this fix didn't quite fix the situation when OneShot is involved.

Let me know which plugin version you experienced this on, and I can also guide you through updating the plugin if that would be helpful.

**Comment by glasser** [comment]
Yes, with the latest. I didn't actually try disabling OneShot and re enabling though, was in a hurry so just recorded today's macro not on the fly.

**Comment by glasser** [comment]
Actually, this still takes effect when I have OneShot disabled. It seems like the Fn from my record key is being applied to my target key (enter).

**Comment by cdisselkoen** [comment]
Hmm, I'm not quite able to reproduce this yet.

If I have this right, the sequence is:

- put `Key_MacroRec` on Fn layer and `Key_MacroPlay` on default layer
- Record a macro to Enter slot
- Attempt to play Enter slot
- Instead of the macro you recorded, the keyboard sends Fn-Enter

Is that correct?

Also, do you have `modsAreSlots` set to its default (`false`), or did you change it to `true`?
